name: Digical Ocean CICD

on:
  push:
    branches: [ "base" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/nacre:$(echo $GITHUB_SHA | head -c7 ) -t  ${{ secrets.REGISTRY_NAME }}/nacre:latest .

      - name: Log in to DigitalOcean Container Registry
        run:
          doctl registry login --expiry-seconds 60

      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push ${{ secrets.REGISTRY_NAME }}/nacre:$(echo $GITHUB_SHA | head -c7 )
          docker push ${{ secrets.REGISTRY_NAME }}/nacre:latest

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            doctl registry login --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            docker pull registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/nacre:latest
            service nacre restart
